CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(150) NOT NULL UNIQUE,
    username VARCHAR(150),
    password VARCHAR(150),
);
CREATE TABLE todo (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	complete BOOLEAN DEFAULT FALSE,
	description TEXT NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);
CREATE TABLE list (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);
CREATE TABLE todo_list (
	todo_id INTEGER,
	list_id INTEGER,
	PRIMARY KEY (todo_id, list_id),
	FOREIGN KEY (todo_id) REFERENCES todo (id) ON DELETE CASCADE,
	FOREIGN KEY (list_id) REFERENCES list (id) ON DELETE CASCADE
);